import { useEffect, useRef, useState, type ChangeEvent } from 'react'
import { CheckCircle2, Database, Download, FileJson, Image as ImageIcon, Import, Upload } from 'lucide-react'
import { cacheFile, getCachedFile } from '../imageCache'

export interface DatasetSourceItem { id:string; prompt?:string; url?:string }
type Img={filename:string;mimeType:string;data:string}
type Item={prompt:string;images:Img[]}
type Dataset={version:number;createdAt?:string;items:Item[]}
type Ref={id:string;filename:string;mimeType:string;cacheKey:string}
type PageItem={id:string;name:string;prompt:string;image:string;images:string[];imageRefs:Ref[]}
type Page={id:string;name:string;createdAt:string;items:PageItem[]}
const KEY='comfyui-console-datasets-v1'
const makeId=(p:string)=>p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,9)
const read=():Page[]=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
const b64=(b:Blob)=>new Promise<string>((ok,no)=>{const r=new FileReader();r.onloadend=()=>ok(r.result as string);r.onerror=no;r.readAsDataURL(b)})
const download=(name:string,json:string)=>{const u=URL.createObjectURL(new Blob([json],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
const validate=(x:any):Dataset=>{if(!x||typeof x!=='object'||!Array.isArray(x.items))throw new Error(!x||typeof x!=='object'?'Invalid JSON object':'Missing or invalid items array');for(const i of x.items){i.prompt=i.prompt==null?'':typeof i.prompt==='string'?i.prompt:String(i.prompt);if(!Array.isArray(i.images))i.images=[];i.images=i.images.filter((v:any)=>v&&typeof v.data==='string'&&v.data.startsWith('data:'))}return x as Dataset}
function Cached({keyId}:{keyId:string}){const[u,setU]=useState('');useEffect(()=>{let o='';let live=true;void getCachedFile(keyId).then(b=>{if(live&&b){o=URL.createObjectURL(b);setU(o)}});return()=>{live=false;if(o)URL.revokeObjectURL(o)}},[keyId]);return u?<img src={u} alt="" loading="lazy"/>:<div className="dataset-image-empty"><ImageIcon size={26}/></div>}

export function DatasetPage({onClose,sourceItems}:{onClose:()=>void;sourceItems:DatasetSourceItem[]}){
 const[pages,setPages]=useState<Page[]>(read),[active,setActive]=useState<string|null>(()=>read()[0]?.id||null),[sel,setSel]=useState<Set<string>>(new Set()),[tab,setTab]=useState<'build'|'pages'>('build')
 const[step,setStep]=useState<'idle'|'upload'|'preview'|'importing'|'complete'>('idle'),[data,setData]=useState<Dataset|null>(null),[err,setErr]=useState(''),[progress,setProgress]=useState([0,0]),[summary,setSummary]=useState<number[]>([])
 const[opts,setOpts]=useState({images:true,prompts:true,dupes:'skip' as 'skip'|'all'}),input=useRef<HTMLInputElement>(null)
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(pages)),[pages])
 const page=pages.find(x=>x.id===active)||null
 const reset=()=>{setStep('idle');setData(null);setErr('');setSummary([])}
 const exportRecords=async(items:DatasetSourceItem[],name='dataset.json')=>{const out:Dataset={version:1,createdAt:new Date().toISOString(),items:[]};for(const x of items){const r:Item={prompt:x.prompt||'',images:[]},b=await getCachedFile(x.id);if(b)r.images.push({filename:x.id+'.png',mimeType:b.type||'image/png',data:await b64(b)});else if(x.url?.startsWith('data:'))r.images.push({filename:x.id+'.png',mimeType:'image/png',data:x.url});out.items.push(r)}download(name,JSON.stringify(out,null,2))}
 const upload=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=z=>{try{setData(validate(JSON.parse(z.target?.result as string)));setErr('');setStep('preview')}catch(e){setErr(e instanceof Error?e.message:'Failed to parse JSON file.')}};r.readAsText(f);e.target.value=''}
 const doImport=async()=>{if(!data)return;setStep('importing');const count=pages.filter(p=>p.name.startsWith('Imported')).length,name=count?'Imported '+(count+1):'Imported',items:PageItem[]=[];let ip=0,ii=0,sd=0,ir=0;for(let n=0;n<data.items.length;n++){const src=data.items[n];if(opts.dupes==='skip'&&src.prompt&&items.some(x=>x.prompt===src.prompt)){sd++;setProgress([n+1,data.items.length]);continue}try{const refs:Ref[]=[];if(opts.images)for(const im of src.images){const blob=await fetch(im.data).then(r=>r.blob()),key=makeId('media_ds');await cacheFile(key,blob);refs.push({id:makeId('img'),filename:im.filename||key+'.png',mimeType:im.mimeType||blob.type||'image/png',cacheKey:key});ii++}if(opts.images||opts.prompts){const prompt=opts.prompts?src.prompt:'',ids=refs.map(x=>x.cacheKey);items.push({id:makeId('item_ds'),name:prompt.split(' ').slice(0,4).join(' ').trim()||'Imported Pose',prompt,image:ids[0]||'',images:ids,imageRefs:refs});if(opts.prompts&&src.prompt)ip++}}catch{ir++}setProgress([n+1,data.items.length])}const p={id:makeId('page_ds'),name,createdAt:new Date().toISOString(),items};setPages(x=>[...x,p]);setActive(p.id);setTab('pages');setSummary([ip,ii,sd,ir]);setStep('complete')}
 const exportPage=async(p:Page)=>{const out:Dataset={version:1,createdAt:new Date().toISOString(),items:[]};for(const i of p.items){const r:Item={prompt:i.prompt,images:[]};for(const im of i.imageRefs){const b=await getCachedFile(im.cacheKey);if(b)r.images.push({filename:im.filename,mimeType:im.mimeType||b.type||'image/png',data:await b64(b)})}out.items.push(r)}download(p.name.replace(/[^a-z0-9]+/gi,'-')+'.json',JSON.stringify(out,null,2))}

 return <section className="dataset-page"><div className="dataset-page-header"><div><h2><Database size={21}/> Datasets</h2><span>Prompt Vault-compatible dataset JSON</span></div><button className="close-btn" onClick={onClose}>×</button></div>
 <div className="dataset-page-tabs"><button className={tab==='build'?'active':''} onClick={()=>setTab('build')}>Build Dataset</button><button className={tab==='pages'?'active':''} onClick={()=>setTab('pages')}>Imported Pages ({pages.length})</button></div>
 {tab==='build'&&<div className="dataset-build-page"><div className="dataset-toolbar"><div><strong>{sel.size} selected</strong><span>{sourceItems.length} completed generations</span></div><div><button onClick={()=>setSel(sel.size===sourceItems.length?new Set():new Set(sourceItems.map(x=>x.id))}>{sel.size===sourceItems.length?'Clear All':'Select All'}</button><button className="dataset-primary" disabled={!sel.size} onClick={()=>void exportRecords(sourceItems.filter(x=>sel.has(x.id)))}><Download size={16}/> Export JSON</button></div></div><div className="dataset-source-list">{sourceItems.length?sourceItems.map(x=><button className={'dataset-source-card'+(sel.has(x.id)?' selected':'')} key={x.id} onClick={()=>setSel(s=>{const n=new Set(s);n.has(x.id)?n.delete(x.id):n.add(x.id);return n})}><b>{sel.has(x.id)?'✓':''}</b><span className="dataset-source-image">{x.url?<img src={x.url} alt=""/>:<ImageIcon size={22}/>}</span><span>{x.prompt||'No prompt saved.'}</span></button>):<div className="dataset-empty">No completed generations available yet.</div>}</div></div>}
 {tab==='pages'&&<div className="dataset-imported-layout"><aside className="dataset-page-list"><button className="dataset-import-button" onClick={()=>setStep('upload')}><Upload size={16}/> Import JSON</button>{pages.map(p=><button className={p.id===active?'dataset-page-list-item active':'dataset-page-list-item'} key={p.id} onClick={()=>setActive(p.id)}><FileJson size={17}/><span><strong>{p.name}</strong><small>{p.items.length} records</small></span></button>)}</aside><div className="dataset-page-content">{page?<><div className="dataset-content-header"><div><h3>{page.name}</h3><span>{page.items.length} records</span></div><button className="dataset-primary" onClick={()=>void exportPage(page)}><Download size={16}/> Export JSON</button></div><div className="dataset-record-grid">{page.items.map(i=><article className="dataset-record" key={i.id}><div className="dataset-record-image">{i.imageRefs[0]?<Cached keyId={i.imageRefs[0].cacheKey}/>:<ImageIcon size={26}/>}</div><div className="dataset-record-body"><strong>{i.name}</strong><p>{i.prompt||'No prompt provided'}</p>{i.imageRefs.length>1&&<span>{i.imageRefs.length} images</span>}</div></article>)}</div></>:<div className="dataset-empty">Import a compatible dataset JSON to create a page.</div>}</div></div>}
 {step!=='idle'&&<div className="dataset-modal-backdrop"><section className="dataset-modal"><div className="dataset-modal-header"><h3><FileJson size={19}/> Import Dataset</h3><button className="close-btn" onClick={reset} disabled={step==='importing'}>×</button></div>
 {step==='upload'&&<div className="dataset-modal-body dataset-upload-state"><Upload size={42}/><h3>Upload Dataset JSON</h3><p>Import images and prompts into a new page.</p><button className="dataset-primary large" onClick={()=>input.current?.click()}><Upload size={17}/> Select dataset.json</button><input ref={input} type="file" accept=".json,application/json" hidden onChange={upload}/>{err&&<div className="dataset-error">{err}</div>}</div>}
 {step==='preview'&&data&&<div className="dataset-modal-body"><div className="dataset-stats"><div><small>Records Found</small><strong>{data.items.length}</strong></div><div><small>Images Found</small><strong>{data.items.reduce((n,x)=>n+x.images.length,0)}</strong></div></div><div className="dataset-preview-list">{data.items.slice(0,50).map((x,i)=><div className="dataset-preview-row" key={i}>{x.images[0]?.data?<img src={x.images[0].data} alt=""/>:<ImageIcon size={18}/>}<p>{x.prompt||'No prompt provided'}</p></div>)}</div><div className="dataset-options"><label><input type="checkbox" checked={opts.images} onChange={e=>setOpts({...opts,images:e.target.checked})}/> Import Images</label><label><input type="checkbox" checked={opts.prompts} onChange={e=>setOpts({...opts,prompts:e.target.checked})}/> Import Prompts</label><div><span>Duplicate Handling</span><label><input type="radio" name="dataset-dupes" checked={opts.dupes==='skip'} onChange={()=>setOpts({...opts,dupes:'skip'})}/> Skip Duplicates</label><label><input type="radio" name="dataset-dupes" checked={opts.dupes==='all'} onChange={()=>setOpts({...opts,dupes:'all'})}/> Import All</label></div></div><div className="dataset-modal-actions"><button onClick={reset}>Cancel</button><button className="dataset-primary" onClick={()=>void doImport()}><Import size={16}/> Import Dataset</button></div></div>}
 {step==='importing'&&<div className="dataset-modal-body dataset-progress"><Database size={42}/><h3>Importing Dataset...</h3><p>Processing record {progress[0]} / {progress[1]}</p><div className="dataset-progress-bar"><span style={{width:(progress[1]?(progress[0]/progress[1])*100:0)+'%'}}/></div></div>}
 {step==='complete'&&<div className="dataset-modal-body dataset-complete"><CheckCircle2 size={46}/><h3>Import Complete</h3><div className="dataset-results"><span>Prompts <strong>{summary[0]}</strong></span><span>Images <strong>{summary[1]}</strong></span><span>Duplicates skipped <strong>{summary[2]}</strong></span><span>Invalid records <strong>{summary[3]}</strong></span></div><button className="dataset-primary large" onClick={reset}>Continue</button></div>}
 </section></div>}
 </section>
}
