export type WorkflowPrompt = Record<string,{inputs:Record<string,any>;class_type:string;_meta?:Record<string,any>}>
const REMOTE_MODE = import.meta.env.VITE_GENERATION_MODE === 'remote'
const COMFY_BASE_URL = import.meta.env.PROD ? 'https://comfyui.tail84bda1.ts.net' : ''
const LAUNCHER_BASE_URL = import.meta.env.PROD ? 'https://comfyui.tail84bda1.ts.net/launcher' : '/launcher'
const REMOTE_API_URL = '/api/runpod'
export type LauncherStatus={ok:boolean;comfyui:'running'|'starting'|'stopped'|string;launcher:string;batFound:boolean;batPath:string}
export async function getLauncherLogs():Promise<string[]>{if(REMOTE_MODE||import.meta.env.PROD)return[];const r=await fetch(`${LAUNCHER_BASE_URL}/logs`,{cache:'no-store'});if(!r.ok)throw new Error(`Launcher logs returned ${r.status}`);const d=await r.json() as {logs?:string[]};return Array.isArray(d.logs)?d.logs:[]}
export async function getLauncherStatus():Promise<LauncherStatus>{if(REMOTE_MODE)return{ok:true,comfyui:'running',launcher:'running',batFound:true,batPath:''};if(import.meta.env.PROD){const r=await getRemoteControlStatus();return{ok:r.ok===true,comfyui:r.comfyui??'stopped',launcher:r.launcher??'unknown',batFound:true,batPath:''}}const r=await fetch(`${LAUNCHER_BASE_URL}/status`,{cache:'no-store'});if(!r.ok)throw new Error(`Launcher returned ${r.status}`);return r.json()}
export async function getComfySystemStats():Promise<any>{if(REMOTE_MODE)return{devices:[]};const r=await fetch(`${COMFY_BASE_URL}/system_stats`,{cache:'no-store'});if(!r.ok)throw new Error(`Could not read ComfyUI system stats (${r.status})`);return r.json()}
export async function waitForComfyReady(timeoutMs=120000):Promise<void>{if(REMOTE_MODE)return;const started=Date.now();while(Date.now()-started<timeoutMs){try{const r=await fetch(`${COMFY_BASE_URL}/system_stats`,{cache:'no-store'});if(r.ok)return}catch{}await new Promise(x=>setTimeout(x,1000))}throw new Error('ComfyUI did not finish starting.')}
export async function startComfyUI():Promise<void>{if(REMOTE_MODE)return;if(import.meta.env.PROD){await startComfyFromPhone();return}const r=await fetch(`${LAUNCHER_BASE_URL}/start`,{method:'POST'});if(!r.ok)throw new Error((await r.text())||`Could not start ComfyUI (launcher ${r.status})`);await waitForComfyReady()}
export async function stopComfyUI():Promise<void>{if(REMOTE_MODE)return;const r=await fetch(`${LAUNCHER_BASE_URL}/stop`,{method:'POST'});if(!r.ok)throw new Error(`Could not stop ComfyUI (launcher ${r.status})`)}
export async function freeComfyMemory():Promise<void>{if(REMOTE_MODE)return;const r=await fetch(`${COMFY_BASE_URL}/free`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({unload_models:true,free_memory:true})});if(!r.ok)throw new Error((await r.text())||`Could not free ComfyUI memory (${r.status})`)}
export async function ensureComfyRunning(){await startComfyUI()}
function getClientId(){const k='comfy-client-id';const e=localStorage.getItem(k);if(e)return e;const id=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);localStorage.setItem(k,id);return id}
async function fileToDataUri(file:File){const b=await file.arrayBuffer();let s='';const a=new Uint8Array(b);for(let i=0;i<a.length;i+=0x8000)s+=String.fromCharCode(...a.subarray(i,i+0x8000));return `data:${file.type||'image/png'};base64,${btoa(s)}`}
export async function queuePrompt(prompt:WorkflowPrompt,remoteImages?:Array<{name:string;file:File}>){if(REMOTE_MODE){const images=await Promise.all((remoteImages||[]).map(async x=>({name:x.name,image:await fileToDataUri(x.file)})));const r=await fetch(REMOTE_API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflow:prompt,images})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Remote generation returned ${r.status}`);if(!d?.id)throw new Error('RunPod did not return a job ID.');return{prompt_id:d.id}}await ensureComfyRunning();const r=await fetch(`${COMFY_BASE_URL}/prompt`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,client_id:getClientId()})});if(!r.ok)throw new Error((await r.text())||`ComfyUI returned ${r.status}`);return r.json() as Promise<{prompt_id:string}>}
export async function getHistory(promptId?:string){if(REMOTE_MODE){if(!promptId)return{};const r=await fetch(`${REMOTE_API_URL}?jobId=${encodeURIComponent(promptId)}`,{cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`RunPod status returned ${r.status}`);if(d.status==='FAILED'||d.status==='CANCELLED')throw new Error(d?.error||d?.output?.errors?.join?.(' ')||`RunPod job ${String(d.status).toLowerCase()}`);if(d.status!=='COMPLETED'||!Array.isArray(d.output?.images))return{};return{[promptId]:{outputs:{remote:{images:d.output.images.map((x:{data?:string;type?:string})=>({filename:x.data||'',subfolder:'',type:x.type==='s3_url'?'remote-url':'remote-base64'}))}}}}}const url=promptId?`${COMFY_BASE_URL}/history/${encodeURIComponent(promptId)}`:`${COMFY_BASE_URL}/history`;const r=await fetch(url);if(!r.ok)throw new Error(`Could not read ComfyUI history (${r.status})`);return r.json()}
export function viewImageUrl(filename:string,subfolder='',type='output'){if(REMOTE_MODE&&(type==='remote-base64'||type==='remote-url'))return type==='remote-base64'?`data:image/png;base64,${filename}`:filename;const p=new URLSearchParams({filename,subfolder,type});return`${COMFY_BASE_URL}/view?${p.toString()}`}
export async function uploadImage(file:File){if(REMOTE_MODE)return{name:file.name,subfolder:'',type:'input'} as const;const f=new FormData();f.append('image',file,file.name);f.append('type','input');f.append('overwrite','true');const r=await fetch(`${COMFY_BASE_URL}/upload/image`,{method:'POST',body:f});if(!r.ok)throw new Error((await r.text())||`Image upload failed (${r.status})`);return r.json() as Promise<{name:string;subfolder:string;type:string}>}
export function connectProgress(promptId:string,onProgress:(value:number,max:number)=>void,onFinished?:()=>void){if(REMOTE_MODE)return()=>{};const proto=window.location.protocol==='https:'?'wss:':'ws:';const base=import.meta.env.PROD?'wss://comfyui.tail84bda1.ts.net':`${proto}//${window.location.host}`;const ws=new WebSocket(`${base}/ws?clientId=${encodeURIComponent(getClientId())}`);ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m?.type==='progress'&&m?.data){const v=Number(m.data.value),x=Number(m.data.max);if(Number.isFinite(v)&&Number.isFinite(x)&&x>0)onProgress(v,x)}if((m?.type==='executing'||m?.type==='executed')&&m?.data?.prompt_id===promptId&&(m?.data?.node===null||m?.type==='executed')){onFinished?.();ws.close()}}catch{}};return()=>ws.close()}
export async function interruptGeneration(){if(REMOTE_MODE)throw new Error('Remote cancellation is not enabled yet.');const r=await fetch(`${COMFY_BASE_URL}/interrupt`,{method:'POST'});if(!r.ok)throw new Error((await r.text())||'Could not stop generation.')}
const REMOTE_CONTROL_URL=import.meta.env.PROD?'https://comfyui.tail84bda1.ts.net/remote':'/remote'
export async function startComfyFromPhone(){if(REMOTE_MODE)return;const r=await fetch(`${REMOTE_CONTROL_URL}/start`,{method:'POST'});if(!r.ok)throw new Error((await r.text())||'Remote start failed')}
export async function getRemoteControlStatus():Promise<any>{if(REMOTE_MODE)return{ok:true,comfyui:'running',launcher:'running'};const r=await fetch(`${REMOTE_CONTROL_URL}/status`,{cache:'no-store'});if(!r.ok)throw new Error(`Remote control returned ${r.status}`);return r.json()}
